baseURL: /
title: 'Wallace and White Technology Solutions, LLC'
theme: hugo-advance
paginate: 6
enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
languageCode: en-us
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
params:
  google_analytics_id: ''
  enable_dark_mode: true
  enable_nested_menu: true
  enable_fixed_header: true
  enable_language_switcher: true
  colors:
    light:
      base: '#f4f5fb'
      base_offset: '#ffffff'
      base_text: '#202020'
      base_text_offset: '#625c5c'
      alt: '#f4f5fb'
      alt_offset: '#CCCCCC'
      alt_text: '#202020'
      alt_text_offset: '#625c5c'
      primary: '#000000'
      primary_offset: '#28274F'
      primary_text: '#79bcff'
      primary_text_offset: '#ffffff'
    dark:
      base: '#1e1e1e'
      base_offset: '#121212'
      base_text: '#ffffff'
      base_text_offset: '#d7d7d7'
      alt: '#1e1e1e'
      alt_offset: '#2f2f2f'
      alt_text: '#fafafa'
      alt_text_offset: '#a8a4a4'
      primary: '#2b5df7'
      primary_offset: '#a62bf7'
      primary_text: '#eeebfc'
      primary_text_offset: '#a7a7a7'
  fonts:
    google_fonts: >-
      https://fonts.googleapis.com/css2?family=Fira+Mono&family=Lato:wght@300;400;700&family=Source+Sans+Pro&display=swap
    heading: Lato
    base: Source Sans Pro
    monospace: Fira Mono
  logo:
    logo: images/logo/logo.svg
    logo_mobile: images/logo/logo-mobile.svg
    logo_invert: images/logo/logo-invert.svg
    logo_invert_mobile: images/logo/logo-mobile-invert.svg
  seo:
    meta_twitter_site: '@zerostaticio'
    meta_twitter_creator: '@zerostaticio'
  footer:
    show_site_title: true
    show_copyright: true
    show_social_media_links: true
    show_languages: false
    enable_menu_footer_primary: true
    footer_primary_menu_title: Product
    enable_menu_footer_secondary: true
    footer_secondary_menu_title: Company
    enable_menu_footer_tertiary: true
    footer_tertiary_menu_title: Support
menu:
  #main:
  #  - name: Buy Now
  #    url: 'https://www.zerostatic.io/theme/hugo-advance/'
  #    weight: 10
  #footer_tertiary:
  #  - name: Buy Now
  #    url: 'https://www.zerostatic.io/theme/hugo-advance/'
  #    weight: 10
languages:
  en:
    weight: 0
    languageName: English
    contentDir: content/en
permalinks:
  posts: 'blog/:year/:month/:title/'
  pages: ':slug/'
taxonomies:
  tag: tags
  category: categories
  portfolio: portfolio
  author: authors
